spring:
  datasource:
    username: root
    password: G2020dbw
    url: jdbc:mysql://localhost:3306/vueblog?userSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
shrio-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
markerhub:
  jwt:
    secret: fe42e520348f86b67cde581c0f9eb5
    expires: 604800
    header: Authorization
