spring:
  datasource:
    username: root
    password: G2020dbw
    url: jdbc:mysql://localhost:3306/vueblog?userSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
